---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "Patrizia Maria Maier"
    affiliation   : "1,2"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "patrizia.maier@charite.de"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization"
      - "Data Curation" 
      - "Formal Analysis" 
      - "Methodology" 
      - "Visualization" 
      - "Software" 
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Iryna Schommartz"
    affiliation   : "3"
    role:
      - "Conceptualization"
      - "Investigation" 
      - "Formal Analysis" 
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Deetje Iggena"
    affiliation   : "1"
    role:
      - "Conceptualization"
      - "Software"
      - "Writing - Review & Editing"
  - name          : "Carsten Finke"
    affiliation   : "1,2"
    role:
      - "Conceptualization"
      - "Funding Acquisition"
      - "Supervision"
      - "Writing - Review & Editing"      
  - name          : "Christoph J. Ploner"
    affiliation   : "1"
    role:
      - "Conceptualization"
      - "Funding Acquisition"
      - "Supervision"
      - "Writing - Review & Editing"       
  - name          : "Yee Lee Shing"
    affiliation   : "3"
    role:
      - "Conceptualization"
      - "Funding Acquisition"
      - "Resources"
      - "Supervision"
      - "Writing - Review & Editing" 
      
affiliation:
  - id            : "1"
    institution   : "Charité - Universitätsmedizin Berlin"
  - id            : "2"
    institution   : "Berlin School of Mind and Brain, Humboldt-Universität zu Berlin"
  - id            : "3"
    institution   : "Goethe Universität Frankfurt/Main"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library(papaja)
library(tidyverse)
library(patchwork)
library(ggrepel)

knitr::read_chunk('../Script_03_Plot_Creator.R')
knitr::read_chunk('../Script_02_Analyzer.R')
```

```{r analysis-preferences}
set.seed(42)
knitr::opts_chunk$set(cache.extra=knitr::rand_seed)
```


# Introduction 

# Methods 

# Results



# Discussion

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
